# Generated by Django 5.2.18 on 2026-10-09 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueprintMetadata',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_key', models.CharField(db_index=True, help_text='Object storage key (e.g. blueprints/{tenant_id}/{year}/{month}/{uuid}_{filename})', max_length=512, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(default='image/png', max_length=100)),
                ('version', models.PositiveIntegerField(db_index=True, default=1)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_blueprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blueprint Metadata',
                'verbose_name_plural': 'Blueprint Metadata',
                'ordering': ['-version', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'title', 'version'], name='blueprints__tenant__2e45eb_idx')],
            },
        ),
    ]
