# Generated by Django 5.2.18 on 2026-10-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprintmetadata',
            name='floor_id',
            field=models.UUIDField(blank=True, db_index=True, help_text="Associated floor UUID (linked to Pradeesh's campus module)", null=True),
        ),
    ]
