# Generated by Django 5.2.18 on 2026-10-10 05:02

import apps.visitors.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorPass',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('visitor_name', models.CharField(max_length=255)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('visitor_phone', models.CharField(max_length=30)),
                ('purpose', models.CharField(max_length=255)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(db_index=True)),
                ('valid_until', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30)),
                ('qr_token', models.CharField(db_index=True, default=apps.visitors.models.generate_secure_qr_token, max_length=128, unique=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_passes', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_passes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_passes', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(help_text='Staff or faculty host member', on_delete=django.db.models.deletion.CASCADE, related_name='hosted_passes', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_passes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Visitor Pass',
                'verbose_name_plural': 'Visitor Passes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('action', models.CharField(choices=[('requested', 'Pass Requested'), ('approved', 'Pass Approved'), ('rejected', 'Pass Rejected'), ('qr_verified', 'QR Verified'), ('check_in', 'Check In'), ('check_out', 'Check Out'), ('cancelled', 'Pass Cancelled'), ('expired', 'Pass Expired')], db_index=True, max_length=30)),
                ('checkpoint_name', models.CharField(blank=True, help_text='e.g. Gate 1, Tower B Lobby', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('scanned_by', models.ForeignKey(blank=True, help_text='Acting user (security, host, admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_visitor_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('visitor_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='visitors.visitorpass')),
            ],
            options={
                'verbose_name': 'Visitor Log',
                'verbose_name_plural': 'Visitor Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visitorpass',
            index=models.Index(fields=['tenant', 'status'], name='visitors_vi_tenant__04bcc1_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorpass',
            index=models.Index(fields=['tenant', 'valid_from', 'valid_until'], name='visitors_vi_tenant__acdec1_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorpass',
            index=models.Index(fields=['host', 'status'], name='visitors_vi_host_id_c72efc_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorpass',
            index=models.Index(fields=['qr_token'], name='visitors_vi_qr_toke_afa5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['tenant', 'action'], name='visitors_vi_tenant__93dde3_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['visitor_pass', 'action'], name='visitors_vi_visitor_31aa41_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['scanned_by', 'created_at'], name='visitors_vi_scanned_8a84f4_idx'),
        ),
    ]
